name: Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: git clone https://github.com/${{ github.repository }} .

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/root/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl version

      - name: Deploy
        run: |
          export FLYCTL_INSTALL="/root/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl deploy --remote-only --app adhahi-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
